version: "3.9"
services:
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3.13-rc-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5
  gateway:
    container_name: gateway_container
    build:
      context: ../api-gateway
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3000:3000
    env_file: ../api-gateway/configs/.env
    environment:
      - DOCKER_ENV=true
      - AUTH_SERVICE_URL=http://auth:3001 # OVERWRITE AUTH_SERVICE_URL IN ENV FILE
      - USER_SERVICE_URL=http://user-profile:3002 # OVERWRITE USER_SERVICE_URL IN ENV FILE
    secrets:
      - jwt_public_key
    volumes:
      - ../api-gateway/src:/app/src # HOT RELOADING
  auth:
    container_name: auth_container
    build:
      context: ../auth
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3001:3001
    env_file: ../auth/configs/.env
    environment:
      - DOCKER_ENV=true
      - API_GATEWAY=http://gateway:3000
      - COMPANY_SERVICE=http://company:3001 # OVERWRITE COMPANY_SERVICE_URL IN ENV FILE
      - USER_SERVICE_URL=http://user-profile:3002 # OVERWRITE USER_SERVICE_URL IN ENV FILE
      - RABBITMQ_ENDPOINT=amqp://myuser:mypassword@rabbitmq:5672 # OVERWRITE USER_RABBITMQ_ENDPOINT SERVICE_URL IN ENV FILE
    secrets:
      - jwt_private_key
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ../auth/src:/app/src
  user-profile:
    container_name: user_profile_container
    build:
      context: ../users
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3002:3002
    env_file: ../users/configs/.env
    environment:
      - DOCKER_ENV=true
      - API_GATEWAY=http://gateway:3000 # OVERWRITE API_GATEWAY_URL IN ENV FILE
      - AUTH_SERVICE_URL=http://auth:3001 # OVERWRITE AUTH_SERVICE_URL IN ENV FILE
    secrets:
      - jwt_public_key
    volumes:
      - ../users/src:/app/src
  notification:
    container_name: notification_container
    build:
      context: ../notification
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3009:3009
    env_file: ../notification/configs/.env
    environment:
      - RABBITMQ_ENDPOINT=amqp://myuser:mypassword@rabbitmq:5672 # OVERWRITE USER_RABBITMQ_ENDPOINT SERVICE_URL IN ENV FILE
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ../notification/src:/app/src
secrets:
  jwt_public_key:
    file: ../api-gateway/public_key.pem
  jwt_private_key:
    file: ../auth/private_key.pem
