name: Deploy API Gateway

on:
  push:
    branches:
      - main
    paths:
      - "api-gateway/**"

defaults:
  run:
    working-directory: api-gateway

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build

      - name: Generate API documentation
        run: yarn gen:all

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./api-gateway/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get the Production Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./api-gateway/build
      
      - name: Ensure Node.js and PM2 are installed
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            if ! type node > /dev/null; then
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
              nvm install 16
              nvm use 16
            fi
            if ! type pm2 > /dev/null; then
              npm install pm2@latest -g
            fi
            node -v
            pm2 -v

      - name: Ensure target directory exists
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p /home/ec2-user/apps
            chown ec2-user:ec2-user /home/ec2-user/apps

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }} # Update as per your setup
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "api-gateway/build/*"
          target: "/home/ec2-user/apps"

      - name: Start 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }} # Update as per your setup
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/apps/api-gateway
            # Check if the PM2 process is running
            if pm2 show api-gateway > /dev/null; then
              echo "Application is running. Restarting..."
              npm run restart
            else
              echo "Application is not running. Starting..."
              npm run start
            fi
